### ISSUE TITLE
Bind Radman to loopback only

### ISSUE THREAD

**Issue by dmgeurts** [netcore-jsa/radman#50]
Given that Radman is a java runtime and doesn't support https. I'm planning to reverse proxy through Nginx, to make hosting Radman on https (tcp/443) easier.

Is there a way to configure Radman to bind to localhost instead of *?

**Comment by tomaskir** [comment]
Hi,

Configuring HTTPS and / or bind address and port are both possible. You can check our Unimus docs for how-to:
https://wiki.unimus.net/display/UNPUB/Configuring+server+port+or+bind+address
https://wiki.unimus.net/display/UNPUB/Unimus+HTTPS+with+a+self-signed+cert

Simply use `/etc/default/radman` to configure RadMan :)

**Comment by dmgeurts** [comment]
Thank you, the following in `/etc/radman/radman.properties` works great:

```
# http port
server.port=8080
server.address=127.0.0.1
```

Using Nginx for SSL as it makes feeding the access logs into a log collector easier; aka closely aligned to other internal sites. And tbh, I don't trust Java... :joy:
